// Service Worker — generated by NeoCode
importScripts('https://www.gstatic.com/firebasejs/10.12.2/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.2/firebase-messaging-compat.js');

const firebaseConfig = {
  apiKey: "AIzaSyCZH225ITSw_JGx8Faq8nxxgzb49SBqrk8",
  authDomain: "neonchat-2df05.firebaseapp.com",
  databaseURL: "https://neonchat-2df05-default-rtdb.firebaseio.com",
  projectId: "neonchat-2df05",
  storageBucket: "neonchat-2df05.firebasestorage.app",
  messagingSenderId: "275702671868",
  appId: "1:275702671868:web:e4235a6991b3ae22276a79"
};
firebase.initializeApp(firebaseConfig);
const messaging = firebase.messaging();

// 🚀 الحل الجذري: إجبار المتصفح على عرض الإشعار برمجياً لتخطي قيود الأندرويد
messaging.onBackgroundMessage(function(payload) {
  const notificationTitle = payload.notification?.title || 'إشعار جديد';
  const notificationOptions = {
    body: payload.notification?.body || 'لديك رسالة جديدة',
    icon: '/icon-192.png',
    badge: '/icon-192.png',
    dir: 'rtl',
    vibrate: [300, 100, 300]
  };
  return self.registration.showNotification(notificationTitle, notificationOptions);
});

// رفعنا الإصدار ليجبر المتصفح ياخد النسخة الجديدة
const CACHE_NAME = 'app-cache-12'; 
const ASSETS = [
  './',
  './index.html',
  './style.css',
  './script.js',
  './icon.png',
  './manifest.json',
  // ضفنا مكاتب فايربيز لهون مشان يفتح التطبيق ويفوت عالمحادثات بدون نت
  'https://www.gstatic.com/firebasejs/10.12.2/firebase-app-compat.js',
  'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth-compat.js',
  'https://www.gstatic.com/firebasejs/10.12.2/firebase-database-compat.js',
  'https://www.gstatic.com/firebasejs/10.12.2/firebase-storage-compat.js',
  'https://www.gstatic.com/firebasejs/10.12.2/firebase-messaging-compat.js'
];

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(
      ASSETS.filter(url => !url.includes('icon.png'))
    ))
  );
  self.skipWaiting();
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE_NAME && k !== 'media-cache').map(k => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', event => {
	  if (event.request.method !== 'GET') return;
	
  // 1. استثناء اتصالات سيرفر فيرسيل بس
  if (event.request.url.includes('vercel.app')) {
    return;
  }

  // 2. تكييش الصوتيات والصور من كلاوديناري مباشرة للعمل بدون نت
  if (event.request.url.includes('cloudinary.com')) {
    event.respondWith(
      caches.match(event.request).then(cached => {
        if (cached) return cached;
        return fetch(event.request).then(response => {
          const clone = response.clone();
          caches.open('media-cache').then(cache => cache.put(event.request, clone));
          return response;
        }).catch(() => {});
      })
    );
    return;
  }

  // 3. باقي الملفات (بما فيها فايربيز)
  event.respondWith(
    caches.match(event.request).then(cached => {
      if (cached) return cached;
      return fetch(event.request).then(response => {
        // شلنا شرط type !== basic لحتى يقبل مكاتب فايربيز الخارجية
        if (!response || response.status !== 200) return response;
        const clone = response.clone();
        caches.open(CACHE_NAME).then(cache => cache.put(event.request, clone));
        return response;
      }).catch(() => caches.match('./index.html'));
    })
  );
});
